// project states
export const PROJECT_STATES = {
  PLANNING: "PLANNING",
  READY: "READY",
  IN_PROGRESS: "IN_PROGRESS",
  CANCELLED: "CANCELLED",
  FINISHED: "FINISHED",
};

// project roles
export const PROJECT_ROLES = {
  NORMAL_USER: "NORMAL_USER",
  PROJECT_MANAGER: "PROJECT_MANAGER",
};

// task states
export const TASK_STATES = {
  PLANNED: "PLANNED",
  IN_PROGRESS: "IN_PROGRESS",
  FINISHED: "FINISHED",
};

// websocket message types
export const MESSAGE_TYPES = {
  FORCED_LOGOUT: "FORCED_LOGOUT",
  FORCED_LOGOUT_FAILED: "FORCED_LOGOUT_FAILED",
  RECEIVED_NOTIFICATION: "RECEIVED_NOTIFICATION",
  NEW_GROUP_MESSAGE: "NEW_GROUP_MESSAGE",
  MARK_AS_READ: "MARK_AS_READ",
  NEW_INDIVIDUAL_MESSAGE: "NEW_INDIVIDUAL_MESSAGE",
};